### ISSUE TITLE
abstract submission

### ISSUE THREAD

**Issue by david-barnett** [bytemal/bytemal-2020#1]
We need:

- [x] a system to submit abstracts (email or a google form or something else?)

- [x]  guidance on what can be submitted (e.g. pdf/ freestanding html page/ link to other project + short summary.... etc.)

- [x] content for the abstract submission guidance page

- [x] dropdown nav-bar for abstract submission main and detailed submission guidance pages

**Comment by marvinm2** [comment]
https://docs.google.com/document/d/15fH_MI5sH63yRPcVbqUupyNQdCdQxCEDaNbWFrFLmX8/edit

**Comment by marvinm2** [comment]
We think about making an abstract template, a standard word document with requirements in there.

**Comment by BartvanSloun** [comment]
Update:
- We updated the abstract template, also incorporating a checkbox for the flashtalks
- Information on the website - ByteMAL 2020 Call for Abstracts.
We will need to add more information on the abstract guidelines, posters. etc. However we don't want to make it too condensed

**Comment by david-barnett** [comment]
we could add further details on a subpage under the submit tab 

(i think configuring a dropdown selection on the navbar should be easy enough with bootstrap [nav-bar)](https://getbootstrap.com/docs/4.5/components/navbar/?#nav)
