### ISSUE TITLE
minor bug: program page margin shift

### ISSUE THREAD

**Issue by david-barnett** [bytemal/bytemal-2020#4]
"program" page uses same template (default) as other pages but everything is shifted a few pixels to the side...

https://bytemal.github.io/bytemal-2020/program

**Comment by marvinm2** [comment]
I don't see it though

**Comment by david-barnett** [comment]
also happens with the submit page now for me! (the submit and program pages are all shifted a few pixels to the left)

reproduced in firefox and edge browsers on windows 10

**Comment by david-barnett** [comment]
fixed, it was caused by appearance of a scrollbar on long pages and not on others, so i just forced the scrollbar to always appear
